site_name: "Building Trusted Digital Services"
site_description: "Learn about the building blocks used to build trusted digital services"
docs_dir: "docs"
repo_url: "https://github.com/bcgov/connected-services-techdocs"
edit_uri: edit/main/getting-started/docs/
nav:
    - index.md
    - purpose-and-value.md
    - building-blocks.md
    - authoritative-data-register.md
    - eligibility-factor-verification.md
    - secure-data-exchange.md
    - api-services-portal.md    
    - integration-toolkit.md
    - privacy-and-security.md
    - governance-and-policy.md
    - roles-and-responsibilities.md
    - limits-and-constraints.md
    - support.md

plugins:
  - techdocs-core
  
markdown_extensions:
    - md_in_html
