site_name: "Secure Data Exchange Documentation"
site_description: "Documentation for Secure Data Exchange (SDX). Coming soon."
docs_dir: "docs"
repo_url: "https://github.com/bcgov/connected-services-techdocs"
edit_uri: edit/main/secure-data-exchange/docs/
nav:
  - Home: index.md
  - Getting Started with SDX:
      - SDX roles and responsibilities: getting-started-with-sdx/sdx-roles-and-responsibilities.md
      - Environments: getting-started-with-sdx/environments.md
      - Publish a service: getting-started-with-sdx/publish-a-service.md
      - Consume a service: getting-started-with-sdx/consume-a-service.md
      - Onboarding process:
          - Overview: getting-started-with-sdx/onboarding-process/onboarding-process.md
          - Onboarding an organization: getting-started-with-sdx/onboarding-process/onboarding-an-organization.md
          - Install an Edge Runtime Group: getting-started-with-sdx/onboarding-process/install-an-edge-runtime-group.md
          - Set Up Organization Signing: getting-started-with-sdx/onboarding-process/set-up-organization-signing.md
          - Managing Subsystems: getting-started-with-sdx/onboarding-process/managing-subsystems.md
          - Managing Services: getting-started-with-sdx/onboarding-process/managing-services.md
          - Connecting a Service: getting-started-with-sdx/onboarding-process/connecting-a-service.md
          - Connection Gateway Patterns: getting-started-with-sdx/onboarding-process/connection-gateway-patterns.md
  - Experimental Features – LAB Only: experimental-features.md
  - Get Support: get-support.md

plugins:
  - techdocs-core

markdown_extensions:
  - md_in_html
